service: nestjs-api

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2
  stage: dev
  environment:
    LOG_LEVEL: info
    POWERTOOLS_DEV: "true"
    NODE_OPTIONS: "--enable-source-maps"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
